# Generated by Django 3.0.4 on 2020-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='poster',
            field=models.CharField(default='bob', max_length=50),
            preserve_default=False,
        ),
    ]
